version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "65432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8089:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  jasperserver:
    image: bitnami/jasperreports:latest
    container_name: jasperserver
    environment:
      JASPERREPORTS_DATABASE_TYPE: postgresql
      JASPERREPORTS_DATABASE_HOST: postgres
      JASPERREPORTS_DATABASE_PORT_NUMBER: 5432
      JASPERREPORTS_DATABASE_USER: admin
      JASPERREPORTS_DATABASE_PASSWORD: admin
      JASPERREPORTS_DATABASE_NAME: mydatabase
      JASPERREPORTS_USERNAME: jasperadmin
      JASPERREPORTS_PASSWORD: bitnami
    ports:
      - "8088:8080"
    depends_on:
      - postgres
    volumes:
      - jasperserver_data:/bitnami/jasperreports

volumes:
  postgres_data:
  pgadmin_data:
  jasperserver_data:
